# -*- coding: utf-8 -*-
"""Algorytmy29.10.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJRbCzERYl6RmDmNbi_ddlcYgfGIb_xH

Napisz funkcję, która przykmuje paramert "n" i zlicza sumę 1 do n
"""

import time


def suma(n):
  return sum(range(1,n+1))



start = time.time()
S = suma(5)
end = time.time()


print(S)

print(f"czas wykonania: {end - start} sekund")

"""Zmierz czas wykonania tej funkcji"""